_wandb:
    value:
        cli_version: 0.21.0
        e:
            gclv339teeb6l00cgwcy3sack9ypjuhc:
                args:
                    - --mixed
                    - --output_dir
                    - adapters/stage1_mix
                codePath: scripts/train_qlora_mistral.py
                codePathLocal: scripts/train_qlora_mistral.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "191125819392"
                email: patrickthomaskidwell@gmail.com
                executable: /home/pkidwell/mistral-venv/bin/python
                git:
                    commit: 1323e2a759f26fdca0f7e377d1c9df6a7a57259b
                    remote: git@github.com:pkidwell22/mistral_qlora.git
                gpu: NVIDIA GeForce RTX 4060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060
                      uuid: GPU-f2bdce56-9bdb-aa77-f3cd-200a55e5e5e2
                host: Patrick
                memory:
                    total: "16680939520"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/pkidwell/mistral_qlora/scripts/train_qlora_mistral.py
                python: CPython 3.12.3
                root: /home/pkidwell/mistral_qlora
                startedAt: "2025-07-18T09:59:50.362751Z"
                writerId: gclv339teeb6l00cgwcy3sack9ypjuhc
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.21.0
            "6": 4.38.2
            "12": 0.21.0
            "13": linux-x86_64
epochs:
    value: 1
lr:
    value: 0.0002
